name: SQLStatements

# When should this workflow run?
on: [push]  # Run this workflow whenever you push code

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use Ubuntu as the virtual machine

    steps:
      - name: Checkout Code  # Step 1: Get your code from GitHub
        uses: actions/checkout@v4

      - name: Install MySQL Client  # Step 2: Install MySQL tools
        run: sudo apt-get update && sudo apt-get install -y mysql-client

      - name: Run SQL Script  # Step 3: Run the SQL script
        run: mysql -h your-db-host -u your-db-user -pyour-db-password < your_script.sql
