name: Deploy SQL Scripts

# Trigger workflow on push
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use an Ubuntu virtual machine

    steps:
      - name: Checkout Code  # Step 1: Get the latest code from GitHub
        uses: actions/checkout@v4

      - name: Install MySQL Client  # Step 2: Install MySQL client to run the SQL script
        run: sudo apt-get update && sudo apt-get install -y mysql-client

      - name: Run SQL Script  # Step 3: Run the SQL script from DatabaseAdministration/SQLStatements
        run: mysql -h $DB_HOST -u $DB_USER -p$DB_PASSWORD DBTest < DatabaseAdministration/SQLStatements/Insert SQLQuery.sql
