name: Deploy SQLite Script

on: [push]

jobs:
  test-sql:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install SQLite
        run: sudo apt-get install sqlite3

      - name: Run SQL Script
        run: sqlite3 mydatabase.db < your_script.sql
